### ISSUE TITLE
Add repoLink URL to POST /projects

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally-API#1]
Summary: Add Repo Link
- [ ]  Add field to model called `repoLink` and type String
- [ ] Add new field to existing Joi validators

**Comment by mct-dev** [comment]
@TheWillG, is `repoLink` a required field?

**Comment by TheWillG** [comment]
@mct-dev optional

**Comment by mct-dev** [comment]
ok.  I'll give this one a shot.

**Comment by TheWillG** [comment]
@mct-dev actually, if we can, let's make the website non-required but the repoLink required. I believe that makes the most sense.

**Comment by mct-dev** [comment]
@TheWillG, I wasn't able to run this locally (mongoose connection issue).  I opened the PR anyway since the change was quite simple.  Maybe give it a try yourself to make sure everything works alright.

**Comment by TheWillG** [comment]
@mct-dev no worries, I'll run it locally to make sure
