### ISSUE TITLE
Add dateCreated field to Projects

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally-API#4]
- [ ] Add dateCreated field to projects in GMT format when they are saved.

**Comment by raul1991** [comment]
I can take a look at it. Is it ok ?

**Comment by TheWillG** [comment]
@raul1991 yes this should be a quick one. Let me know if you have any questions

**Comment by raul1991** [comment]
While I was running the project, I got the following error

> sh: 1: node: not found
> 
> npm ERR! Linux 4.15.0-34-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! coderally-api@1.0.0 start: `node index.js`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the coderally-api@1.0.0 start script 'node index.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the coderally-api package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node index.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs coderally-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls coderally-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/erahbaw/CodeRally-API/npm-debug.log
> 

I fixed by creating a symlink to my nodejs and now I got the following error

> const { logger, port } = require("./lib/config");
>       ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3
> 
> npm ERR! Linux 4.15.0-34-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! coderally-api@1.0.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the coderally-api@1.0.0 start script 'node index.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the coderally-api package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node index.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs coderally-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls coderally-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/erahbaw/CodeRally-API/npm-debug.log
> 

# Environment
OS - Ubuntu 16.04
npm version - 4.2.6

**Comment by ahhmarr** [comment]
[#5](https://github.com/TheWillG/CodeRally-API/pull/5)
