### ISSUE TITLE
Change Tech to string array

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally-API#6]
- [ ] change model definition to string array

- [ ] change validation for POSTing project data to string array

**Comment by Ilyeo** [comment]
@TheWillG could I take this issue?

**Comment by TheWillG** [comment]
@Ilyeo we are closing this issue because the requirements have changed on the frontend.  Check back later soon for more issues if you still want to contribute....we are always posting small, short issues for Hacktoberfest.

**Comment by Ilyeo** [comment]
@TheWillG roger that
